export { HeaderComponent } from './header/header.component';
export { HeroComponent } from './hero/hero.component';
export { TaglineComponent } from './tagline/tagline.component';
export { AboutComponent } from './about/about.component';
export { ServicesComponent } from './services/services.component';
export { TestimonialsComponent } from './testimonials/testimonials.component';
export { EstimationComponent } from './estimation/estimation.component';
export { ContactComponent } from './contact/contact.component';
export { FooterComponent } from './footer/footer.component';
